package utils {

	public class Namen {

		public static function getLastname(percent:Number) {
			return lastnames[Math.floor(percent * lastnames.length)];
		}

		public static function getRandomLastname() {
			return lastnames[getRandom(lastnames.length)];
		}

		public static function getRandomFirstname() {
			return firstnames[getRandom(firstnames.length)];
		}

		public static function getRandomCity() {
			if (getRandom(100) < 10) {
				return cities[getRandom(cities.length)];
			} else {
				return '';
			}
		}

		public static function getRandomCompany() {
			if (getRandom(100) < 10) {
				return companies[getRandom(companies.length)];
			} else {
				return '';
			}
		}

		private static function getRandom(to:int) {
			return Math.floor(Math.random() * to);
		}

		// Selbst "ausgedacht".
		private static var cities:Array = [
			'Gummersbach', 'Köln', 'Bonn', 'Koblenz', 'Düsseldürf', 'New York', 'Manchaster'
		];
		// Selbst "ausgedacht".
		private static var companies:Array = [
			'FH Köln', 'IT hier und da', 'Audi', 'Ferchau', 'Sparkasse'
		];

		// Vornamen bestehen aus:
		// * Top 100 von http://de.wiktionary.org/wiki/Wiktionary:Deutsch/Liste_der_h%C3%A4ufigsten_m%C3%A4nnlichen_Vornamen_Deutschlands
		// * Top 100 von http://de.wiktionary.org/wiki/Wiktionary:Deutsch/Liste_der_h%C3%A4ufigsten_weiblichen_Vornamen_Deutschlands

		private static var firstnames:Array = [
			'Albert',
			'Alexander',
			'Alexandra',
			'Alfred',
			'Alois',
			'Andrea',
			'Andreas',
			'Angela',
			'Angelika',
			'Anita',
			'Anja',
			'Anke',
			'Anna',
			'Anneliese',
			'Annemarie',
			'Annette',
			'Anni',
			'Anton',
			'Astrid',
			'Axel',
			'Barbara',
			'Beate',
			'Bernd',
			'Bernhard',
			'Bettina',
			'Birgit',
			'Brigitte',
			'Bruno',
			'Bärbel',
			'Charlotte',
			'Christa',
			'Christel',
			'Christian',
			'Christiane',
			'Christina',
			'Christine',
			'Christoph',
			'Claudia',
			'Cornelia',
			'Dagmar',
			'Daniel',
			'Daniela',
			'Detlef',
			'Dieter',
			'Dietmar',
			'Dirk',
			'Doris',
			'Eberhard',
			'Edith',
			'Elfriede',
			'Elisabeth',
			'Elke',
			'Else',
			'Erich',
			'Erika',
			'Erna',
			'Ernst',
			'Erwin',
			'Eva',
			'Frank',
			'Franz',
			'Friedrich',
			'Fritz',
			'Gabriele',
			'Georg',
			'Gerd',
			'Gerda',
			'Gerhard',
			'Gertrud',
			'Gisela',
			'Gudrun',
			'Günter',
			'Günther',
			'Hannelore',
			'Hans',
			'Harald',
			'Hartmut',
			'Hedwig',
			'Heidi',
			'Heike',
			'Heiko',
			'Heinrich',
			'Heinz',
			'Helene',
			'Helga',
			'Helmut',
			'Herbert',
			'Hermann',
			'Hilde',
			'Hildegard',
			'Holger',
			'Horst',
			'Hubert',
			'Ilse',
			'Inge',
			'Ingeborg',
			'Ingo',
			'Ingrid',
			'Irene',
			'Iris',
			'Irmgard',
			'Jens',
			'Joachim',
			'Johann',
			'Johanna',
			'Johannes',
			'Josef',
			'Jutta',
			'Jörg',
			'Jürgen',
			'Karin',
			'Karl',
			'Katharina',
			'Katja',
			'Katrin',
			'Kerstin',
			'Klaus',
			'Konrad',
			'Kurt',
			'Lieselotte',
			'Lothar',
			'Ludwig',
			'Manfred',
			'Manuela',
			'Margarete',
			'Margot',
			'Maria',
			'Marianne',
			'Mario',
			'Marion',
			'Markus',
			'Martha',
			'Martin',
			'Martina',
			'Matthias',
			'Melanie',
			'Michael',
			'Michaela',
			'Monika',
			'Nicole',
			'Norbert',
			'Olaf',
			'Oliver',
			'Otto',
			'Paul',
			'Peter',
			'Petra',
			'Rainer',
			'Ralf',
			'Regina',
			'Reiner',
			'Reinhard',
			'Reinhold',
			'Renate',
			'Richard',
			'Rita',
			'Robert',
			'Roland',
			'Rolf',
			'Rosemarie',
			'Roswitha',
			'Rudolf',
			'Ruth',
			'Sabine',
			'Sandra',
			'Siegfried',
			'Sigrid',
			'Silke',
			'Silvia',
			'Simone',
			'Sonja',
			'Stefan',
			'Stefanie',
			'Steffen',
			'Stephan',
			'Susanne',
			'Sven',
			'Sylvia',
			'Tanja',
			'Thomas',
			'Torsten',
			'Udo',
			'Ulrich',
			'Ulrike',
			'Ursula',
			'Ute',
			'Uwe',
			'Volker',
			'Waldemar',
			'Walter',
			'Waltraud',
			'Werner',
			'Wilfried',
			'Wilhelm',
			'Willi',
			'Wolfgang',
		];

		// Nachnamen bestehen aus:
		// * Top 100 von http://de.wikipedia.org/wiki/Liste_der_h%C3%A4ufigsten_Familiennamen_in_Deutschland

		private static var lastnames:Array = [
			'Albrecht',
			'Arnold',
			'Bauer',
			'Baumann',
			'Beck',
			'Becker',
			'Berger',
			'Bergmann',
			'Brandt',
			'Braun',
			'Busch',
			'Böhm',
			'Dietrich',
			'Engel',
			'Fischer',
			'Frank',
			'Franke',
			'Friedrich',
			'Fuchs',
			'Graf',
			'Gro',
			'Günther',
			'Haas',
			'Hahn',
			'Hartmann',
			'Heinrich',
			'Herrmann',
			'Hoffmann',
			'Hofmann',
			'Horn',
			'Huber',
			'Jung',
			'Jäger',
			'Kaiser',
			'Keller',
			'Klein',
			'Koch',
			'Kraus',
			'Krause',
			'Krämer',
			'Krüger',
			'Kuhn',
			'Köhler',
			'König',
			'Kühn',
			'Lang',
			'Lange',
			'Lehmann',
			'Lorenz',
			'Ludwig',
			'Maier',
			'Martin',
			'Mayer',
			'Meier',
			'Meyer',
			'Möller',
			'Müller',
			'Neumann',
			'Otto',
			'Peters',
			'Pfeiffer',
			'Pohl',
			'Richter',
			'Roth',
			'Sauer',
			'Schmid',
			'Schmidt',
			'Schmitt',
			'Schmitz',
			'Schneider',
			'Scholz',
			'Schreiber',
			'Schröder',
			'Schubert',
			'Schulte',
			'Schulz',
			'Schulze',
			'Schumacher',
			'Schuster',
			'Schwarz',
			'Schäfer',
			'Seidel',
			'Simon',
			'Sommer',
			'Stein',
			'Thomas',
			'Vogel',
			'Vogt',
			'Voigt',
			'Wagner',
			'Walter',
			'Weber',
			'Wei',
			'Werner',
			'Winkler',
			'Winter',
			'Wolf',
			'Wolff',
			'Ziegler',
			'Zimmermann'
		];
	}

}
